### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by Jerakin** [britzl/defcon#3]
Writing `commands` in the console does nothing. If I write `print("Hello")` it shows in Defolds Console.

**Comment by britzl** [comment]
Hmm, ok, and the same works on osx?

Perhaps you could help me by stepping through the code from this point and see where it fails: https://github.com/britzl/defcon/blob/master/defcon/console.lua#L131

**Comment by Jerakin** [comment]
Did it yesterday and this doesn't seem to do anything 
```return M.server.json('{ "response": "' .. utils.urlencode(tostring(response)) .. '" }\r\n')```
But ```utils.urlencode(tostring(response))``` do have the correct value

**Comment by Jerakin** [comment]
It behaved the same way on the mac. So I thought it was the browser, it totally was. Works fine on safari but doesn't print anything in on Firefox

**Comment by britzl** [comment]
DefCon uses the ReadableStream API which isn't supported by all browsers and in the case of Firefox it needs to be enabled in about:config. Refer to the browser compatibility chart for more information: https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream#Browser_compatibility

Added new Requirements section in the readme.
