### ISSUE TITLE
Support for multi-line command

### ISSUE THREAD

**Issue by Jerakin** [britzl/defcon#7]
Sometimes when I am bug hunting I have a setup of commands I want to try in a row.

I want to be able to write something like `module.command;module.other_command 1 2;module.other_command 2 1` and have defcon parse it "line by line".

**Comment by rocamocha** [comment]
Just curious, could creating a 'middleman' module that just contains the other module commands with it's own commands that are predefined lists of commands be a viable workaround to not having this feature?

**Comment by britzl** [comment]
> Just curious, could creating a 'middleman' module that just contains the other module commands with it's own commands that are predefined lists of commands be a viable workaround to not having this feature?

Yes, I think that is a viable workaround! Closing.
